### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by den-run-ai** [peteut/ipython-file-upload#13]
```
dta@dta-Inspiron-N5050 ~ $ jupyter nbextension install --py fileupload
Installing /home/dta/anaconda3/lib/python3.5/site-packages/fileupload/static -> fileupload
Traceback (most recent call last):
  File "/home/dta/anaconda3/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/dta/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/dta/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/home/dta/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 952, in start
    super(NBExtensionApp, self).start()
  File "/home/dta/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/dta/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 730, in start
    self.install_extensions()
  File "/home/dta/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 710, in install_extensions
    logger=self.log)
  File "/home/dta/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 239, in install_nbextension_python
    destination=dest, logger=logger
  File "/home/dta/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 140, in install_nbextension
    ensure_dir_exists(nbext)
  File "/home/dta/anaconda3/lib/python3.5/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/home/dta/anaconda3/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/dta/anaconda3/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'
```

**Comment by den-run-ai** [comment]
Ok finally I got the notebook upload button working, but in the system python installation (using sudo). The Anaconda installation in the user space is giving the error above.

This command is missing in your tutorial, but jupyter requires this for extension to work.

`[sudo] jupyter nbextension enable --py --sys-prefix widgetsnbextension`

**Comment by peteut** [comment]
Should we refer to [Notebook extensions](http://jupyter.readthedocs.io/en/latest/migrating.html?highlight=nbextension#notebook-extensions), as in some cases the `--user` flag or `sudo` right are required?

**Comment by den-run-ai** [comment]
@peteut that article in link is pretty lengthy, what do you mean in the essence with your last sentence?
